### ISSUE TITLE
Increase size of MEGA level sponsors

### ISSUE THREAD

**Issue by zackharley** [qhacks/qhacks-website#10]
Size of MEGA sponsors (RBC, RateHub, .Tech, etc) are too small compared to the next tier.

**Comment by ccrowley96** [comment]
@zackharley How's this?  Are there other tier size differences?  Or is it just MEGA vs normal sponsor?
<img width="1142" alt="screen shot 2017-10-15 at 8 31 15 pm" src="https://user-images.githubusercontent.com/18181049/31590962-d4396802-b1e7-11e7-85cd-9bb2d604858e.png">

**Comment by ccrowley96** [comment]
@zackharley Here's another version:

<img width="1221" alt="screen shot 2017-10-15 at 9 04 38 pm" src="https://user-images.githubusercontent.com/18181049/31591317-87f752ce-b1ec-11e7-927e-1bec71d48b49.png">

**Comment by ccrowley96** [comment]
@zackharley **Something went wrong in the rebase / merge.  The live site has duplicate logos in the wrong places!**

**Comment by RobertWSaunders** [comment]
@zackharley @ccrowley96 I still think there needs to be a bigger distinction between tera, giga, mega, startup etc..., look at https://hackthenorth.com/ for example, very tasteful, right now it appears to look like all the logos are the same tier.
