### ISSUE TITLE
Create mobile version of EventSchedule

### ISSUE THREAD

**Issue by rosslh** [qhacks/qhacks-website#107]
## Summary

Make event schedule compress to fit on small screen sizes

### Example

<img src="https://user-images.githubusercontent.com/8635605/46888670-225b6580-ce2f-11e8-9c1f-2d7fb4205a7b.png" width="30%">

### Motivation

The component should match the mobile mock-ups!

**Comment by RobertWSaunders** [comment]
Nice!
