### ISSUE TITLE
Give EventSchedule table a fixed height

### ISSUE THREAD

**Issue by rosslh** [qhacks/qhacks-website#108]
## Summary

The EventSchedule component's table should not change size when switching days

### Motivation

The way the table changes size prevents switching between days from looking smooth

**Comment by RobertWSaunders** [comment]
Nice!

**Comment by joeytepp** [comment]
Might also be nice to add a slight delay to the text changing, noticed it can be a little jarring because the text moves a lot faster than the slider, maybe worth considering!

**Comment by RobertWSaunders** [comment]
Going to close this because we don't need to focus on this!
