### ISSUE TITLE
DaySwitcher does not work on Netlify after page reload

### ISSUE THREAD

**Issue by rosslh** [qhacks/qhacks-website#109]
## Description

After reloading [dev.qhacks.io](https://dev.qhacks.io) in Firefox, any interaction with DaySwitcher does nothing.

This issue has been challenging to try to debug because React dev tools also stop working after reloading the page.

### Expected Behavior

Clicking a day option in the DaySwitcher should change both DaySwitcher and EventSchedule's state.

### Actual Behavior

Clicking a day option in the DaySwitcher does nothing.

### Steps to Reproduce

1. Go to https://dev.qhacks.io in Firefox

2. Reload the page

3. Try to use the DaySwitcher component

4. Open React dev tools and observe that it says `Waiting for roots to load...`

### Environment

- Firefox 62.0.3
- Netlify

This does not occur locally.
This does not occur on Chrome.

**Comment by rosslh** [comment]
This also applies to the Speakers component added in #106

**Comment by joeytepp** [comment]
Damn that is not good 😕. I assume it works for regular React apps?

**Comment by rosslh** [comment]
@RobertWSaunders fixed by reinstalling Firefox! Thanks for checking on your machine.

**Comment by RobertWSaunders** [comment]
Awesome, glad this was resolved!
