### ISSUE TITLE
Add functionality and states to mailing list signup

### ISSUE THREAD

**Issue by RobertWSaunders** [qhacks/qhacks-website#116]
## Summary

Add in functionality and states to the newsletter signup forms! 

### Motivation

Make it a functioning piece of the website.

**Comment by RobertWSaunders** [comment]
@rosslh I've talked to Courtney and she will be making the states very shortly and putting them in Zeplin.

**Comment by RobertWSaunders** [comment]
Courtney updated Zeplin! See below:

<img width="1086" alt="screen shot 2018-10-13 at 9 37 05 pm" src="https://user-images.githubusercontent.com/13367451/46911641-2fac4900-cf30-11e8-943c-da07356d3d03.png">

**Comment by rosslh** [comment]
Looks great! I'll starting working on this soon
