### ISSUE TITLE
Make menu sticky at top and appear from scrolling

### ISSUE THREAD

**Issue by RobertWSaunders** [qhacks/qhacks-website#117]
## Summary

Lets make the menu sticky at the top once it goes out of view from the top. See the image below: 

<img width="686" alt="screen shot 2018-10-13 at 8 17 16 pm" src="https://user-images.githubusercontent.com/13367451/46911271-ff12e200-cf24-11e8-9bcf-600a1138140d.png">

NOTE: There are a couple of animations and key things to know, see below:

- The current section the user is in should be bolded blue.
- There is hover line animation on menu items you hover over them
- The sticky menu is translucent
- When you scroll down the sticky menu should be hidden
- When you scroll up the sticky menu should be shown

### Motivation

Match the mocks!

**Comment by RobertWSaunders** [comment]
Also the menu currently doesn't take you to the section you press on or have the hover line animation.

**Comment by joeytepp** [comment]
Do you think the mobile header should be a separate issue and PR or does it fall under the scope of this one?

**Comment by RobertWSaunders** [comment]
We could break it down into many issues?

**Comment by joeytepp** [comment]
Yea true, probably would be too big for one PR sounds good 👌
