### ISSUE TITLE
Update Hacker Testimonial cards to have styles matching mocks

### ISSUE THREAD

**Issue by RobertWSaunders** [qhacks/qhacks-website#137]
## Summary

Things to change to match the mocks of the Hacker Testimonial cards (refer to images too):

- the line height in the quotes should be larger
- the project name should be blue
- the project name should link out to the project on dev post

Ours:

<img width="564" alt="screen shot 2018-10-21 at 6 20 20 pm" src="https://user-images.githubusercontent.com/13367451/47273231-2ab64d80-d55f-11e8-8a11-026273c92032.png">

Mocks:

<img width="574" alt="screen shot 2018-10-21 at 6 20 16 pm" src="https://user-images.githubusercontent.com/13367451/47273235-2f7b0180-d55f-11e8-8e3a-55b4d2279818.png">

### Motivation

Match the mocks!

**Comment by rosslh** [comment]
@RobertWSaunders is this good to close based on your changes?

**Comment by RobertWSaunders** [comment]
Yep! Closing!
