### ISSUE TITLE
Scrolling on MobileMenu does not behave as expected on iOS Safari

### ISSUE THREAD

**Issue by joeytepp** [qhacks/qhacks-website#163]
## Description
When opening the mobile menu on loading the screen, scrolling is still enabled, however upon closing and reopening it scrolling is now disabled

### Expected Behavior
I should not be able to scroll through the page when the mobile menu is open

### Actual Behavior
I am able to scroll through the page when opening the mobile menu the first time, but not any subsequent times

### Steps to Reproduce

1. Load the website on iOS Safari

2. Open the mobile menu after the page has loaded and scroll through the page, noting that the background elements are scrolling

3. Close and reopen the mobile menu, try scroll again and notice that scrolling is now locked

### Environment

- Version:
- Platform: iOS Safari

**Comment by RobertWSaunders** [comment]
Is this fixed?

**Comment by joeytepp** [comment]
No, there's a bug where you can still scroll the first time you open it but can't scroll after opening it any subsequent times

**Comment by RobertWSaunders** [comment]
Ah, are we planning to solve this before release?

**Comment by joeytepp** [comment]
Ideally yes, I'll set up a new branch for testing

**Comment by joeytepp** [comment]
Fixed! #169
