### ISSUE TITLE
Make buttons link to their respective locations

### ISSUE THREAD

**Issue by RobertWSaunders** [qhacks/qhacks-website#171]
## Summary

The login buttons, "listen" buttons don't do anything, can we make them link out to their respective places.

It might make sense to refactor them to be anchors.

### Motivation

Make buttons do what they are supposed to do!

**Comment by rosslh** [comment]
Where should the apply button link? https://app.qhacks.io/apply?

**Comment by RobertWSaunders** [comment]
Yeah for now!
