### ISSUE TITLE
Fix bug where ActionButton's colour only transitions smoothly on mouse-over, not mouse-leave 

### ISSUE THREAD

**Issue by rosslh** [qhacks/qhacks-website#173]
## Description

Fix bug where ActionButton's colour only transitions smoothly on mouse-over, not mouse-leave 

### Expected Behavior

ActionButton's colour should transition smoothly on mouse-over and mouse-leave

### Actual Behavior

ActionButton's colour only transitions smoothly on mouse-over, not mouse-leave 

### Steps to Reproduce

1. Mouse-over an ActionButton (note that the colour transitions smoothly)

2. Move your mouse off of the button (note that the colour abruptly changes)

### Environment

- Version: 63.0
- Platform: Firefox

**Comment by RobertWSaunders** [comment]
Nice nice! I was going to make this!
