### ISSUE TITLE
Add 404 Page Error

### ISSUE THREAD

**Issue by noahifergan** [qhacks/qhacks-website#177]
## Summary

Currently this is the default:
![screen shot 2018-10-29 at 6 36 25 pm](https://user-images.githubusercontent.com/25311106/47684546-9de84100-dba9-11e8-94bd-01b534afcf62.png)

We should try to get the logo on it at least and talk to Taylor about including a jokes message.

**Comment by RobertWSaunders** [comment]
Lets make sure to add the right labels/projects/milestones next time! Also sticking to the template helps as well! Thanks for making this issue!
