### ISSUE TITLE
Sponsor logos responsive scaling problem

### ISSUE THREAD

**Issue by ccrowley96** [qhacks/qhacks-website#4]
- [ ] Resolution width between 961 - 991 px left align logos in their own row.
- [ ] Vertical distance between logos is inconsistent

**Comment by zackharley** [comment]
Suggestion:

You can make those two action items a checklist if you want

- [ ] Resolution width between 961 - 991 px left align logos in their own row.
- [ ] Vertical distance between logos is inconsistent

**Comment by zackharley** [comment]
I mean it would be better once we identify a proper solution to put those as a checklist, but I think that adding the to-dos for the ticket are always a good idea
