### ISSUE TITLE
Add security protocol (https) to qhacks.io

### ISSUE THREAD

**Issue by ccrowley96** [qhacks/qhacks-website#5]
@zackharley I can work on this, but I'll need access to the domain provider!

**Comment by zackharley** [comment]
Perfect, I'll get that to you ASAP

**Comment by RobertWSaunders** [comment]
@zackharley and I talked about this, because of GitHub restrictions they don't allow secure sites that have custom domains, so we are going to host the site on GCP and then use Let's Encrypt.

**Comment by zackharley** [comment]
HTTPS is implemented, but there is no automatic upgrade to HTTPS from HTTP. Could be solved by moving to GAE instead of Google Cloud Buckets.

**Comment by RobertWSaunders** [comment]
@zackharley we should do this soon

**Comment by RobertWSaunders** [comment]
About to move over to Netlify which gives us HTTPS for free, closing this.
