### ISSUE TITLE
add google analytics click tracking to partner logos

### ISSUE THREAD

**Issue by RobertWSaunders** [qhacks/qhacks-website#7]
Add tracked clicked events to partner logos in google analytics, this will provide deeper insights to our partners.

**Comment by zackharley** [comment]
@RobertWSaunders Is this to add Google Analytics for click tracking? I think this may have been too ambiguous (see #8)

**Comment by RobertWSaunders** [comment]
@zackharley My apologies, will add a description, was on the plane and wanted to add this before I forgot. Yeah you are correct, we need to setup a strong Google analytics portfolio this year to provide deeper insights to our sponsors, this is something other hackathons do. Not hard to setup but will require a good effort.

**Comment by RobertWSaunders** [comment]
This is complete and live on the site! Moving forward try to implement event tracking in a similar and organized way, the partner logos have been put into a nice event category called partner logos. This allows for better tracking. 🎉
